spring:
  application:
    name: spring-cloud-config-server
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
    encoding: utf-8
    cache-duration: PT1S

server:
  port: 8080

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
